#!/bin/bash

# Expect base collection path as an argument
BASE_COLLECTION_PATH=$1

# Use PWD as base path if no argument is passed
if [[ ${BASE_COLLECTION_PATH} == "" ]]; then
    BASE_COLLECTION_PATH=$(pwd)
fi

CEPH_COLLLECTION_PATH="${BASE_COLLECTION_PATH}/ceph"

ceph_resources=()

ceph_resources+=(cephblockpools)
ceph_resources+=(cephclusters)
ceph_resources+=(cephfilesystems)
ceph_resources+=(cephnfses)
ceph_resources+=(cephobjectstores)
ceph_resources+=(cephobjectstoreusers)

# Inspecting ceph related custom resources for all namespaces 
for resource in ${ceph_resources[@]}; do
    /usr/bin/openshift-must-gather --base-dir=${CEPH_COLLLECTION_PATH} inspect ${resource} --all-namespaces
done

# Inspecting the namespace where ceph-cluster is installed
for ns in $(oc get cephcluster --all-namespaces --no-headers | awk '{print $1}'); do
    /usr/bin/openshift-must-gather --base-dir=${CEPH_COLLLECTION_PATH} inspect ns/${ns}
done

ceph-medic check | tee ${CEPH_COLLLECTION_PATH}/ceph-medic-report.txt