#!/bin/bash

# Resource List
resources=()

# Add general resources to list if necessary 

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
    /usr/bin/openshift-must-gather inspect ${resource}
done

# Call other gather scripts
/usr/bin/gather_noobaa_resources
